"""add headline and summary to topics

Revision ID: 72d98dc54a2d
Revises: 6167116840e9
Create Date: 2026-07-12 02:58:35.245841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d98dc54a2d'
down_revision: Union[str, Sequence[str], None] = '6167116840e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('headline', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'summary')
    op.drop_column('topics', 'headline')
    # ### end Alembic commands ###
